# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QUser',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
    ]
