# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v_1_0', '0002_auto_20161003_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='qbpost',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
