# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v_1_0', '0005_auto_20161008_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='QBPostPic',
            fields=[
                ('pic_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pic_url', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='qbpost',
            name='img_url',
        ),
        migrations.AddField(
            model_name='qbpostpic',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_v_1_0.QBPost'),
        ),
    ]
